#!/usr/bin/env bash

case "$1" in
    "d")
        while read -r line; do
            trash "$line"
        done
    ;;
    "w")
        read -r line
        switch-wallpaper "$(realpath "$line")"
    ;;
esac
