set-option -g default-shell /bin/zsh
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{6}%*%d:%p2%{256}%*%{65536}%/%d:%p3%{256}%*%{256}%/%d:%p4%d;7m'
set -gq allow-passthrough on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'Morantron/tmux-fingers'
set -g @fingers-key o
set -g @fingers-skip-wizard 1

unbind-key C-b
set-option -g prefix C-q
bind-key C-q send-prefix

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind q kill-pane
bind x kill-window
unbind &

setw -g mode-keys vi
bind e copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi C-u send-keys -X page-up
bind -T copy-mode-vi C-d send-keys -X page-down
unbind [

set -g mouse on

bind -n M-H select-pane -L
bind -n M-L select-pane -R
bind -n M-K select-pane -U
bind -n M-J select-pane -D

set -g base-index 1
setw -g pane-base-index 1

setw -g automatic-rename on
set -g renumber-windows on

set -g set-titles on

set-option -g status-right ""

bind w display-popup -h 90% -w 90% -E "tms"
bind N display-popup -h 90% -w 90% -E "rustnet"
bind S display-popup -h 90% -w 90% -E "lazysql"
bind d display-popup -h 90% -w 90% -E "lazydocker"
bind g display-popup -h 90% -w 90% -E "lazygit"
bind h display-popup -h 90% -w 90% -E "gh-dash"
bind j display-popup -h 90% -w 90% -E "lazyjj"
bind J display-popup -h 90% -w 90% -E "lazyjournal"
bind k display-popup -h 90% -w 90% -E "k9s"
bind m display-popup -h 90% -w 90% -E "~/projects/arch-dotfiles/toggles/menu.sh --fzf"
bind n display-popup -h 90% -w 90% -E "netscanner"
bind p display-popup -h 90% -w 90% -E "btop"
bind t display-popup -h 90% -w 90% -E "taskwarrior-tui"
bind z display-popup -h 90% -w 90% -E "zsh"

run '~/.tmux/plugins/tpm/tpm'

source-file -q ~/.cache/wal/colors-tmux.conf
