# only changed keys; colors are 0xSSRRGGBB, SS = styling
full_color = true

fg = 0x0039BAE6
border_fg = 0x0039BAE6

bg = 0x000B0E14

error_fg = 0x00F07178
error_bg = 0x000B0E14

hide_borders = false
hide_key_hints = false

box_title = [ ACCESS ]

clock = %H:%M:%S

asterisk = *

clear_password = true

default_input = login
save = true

margin_box_h = 2
margin_box_v = 1

# only hyprland (uwsm) and plasma, plus ly's built-in shell; hide x11 and xinitrc
waylandsessions = /etc/ly/sessions
xsessions = null
xinitrc = null
