# only changed keys; colors are 0xSSRRGGBB, SS = styling
full_color = true

animation = matrix

cmatrix_fg = 0x001C6E8C
cmatrix_head_col = 0x0059C2FF

fg = 0x0039BAE6
border_fg = 0x0039BAE6

bg = 0x000B0E14

error_fg = 0x00F07178
error_bg = 0x000B0E14

# readable text over the rain
blank_box = true

hide_borders = false
hide_key_hints = true

box_title = [ ACCESS ]

clock = %H:%M:%S

asterisk = *

clear_password = true

default_input = login
save = true

margin_box_h = 2
margin_box_v = 1
