#!/usr/bin/env bash
# end-to-end: fresh arch vm, archinstall, local working tree (or github master with --master), ./install.sh; exits 1 on any failure
exec "$(dirname "$(readlink -f "$0")")/vm-test/vm-test.py" run "$@"
