#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
	{ on = [ "g", "h" ], run = "cd ~",         desc = "Go home" },
	{ on = [ "g", "c" ], run = "cd ~/.config", desc = "Go to ~/.config" },
	{ on = [ "g", "p" ], run = "cd ~/projects", desc = "Go to ~/projects" },
	{ on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },
]
