export DO_NOT_TRACK=1

source ~/.cache/wal/colors.sh

fpath=(~/.zsh/completions $fpath)
export ZSH_DISABLE_COMPFIX=true
export ZSH_COMPDUMP="$HOME/.zcompdump"

ZSH=/usr/share/oh-my-zsh/
ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi
plugins=(aws docker docker-compose fzf git jj mise nmap node npm rust sudo terraform)
source $ZSH/oh-my-zsh.sh

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

zinit ice wait lucid
zinit light Aloxaf/fzf-tab

zinit ice wait lucid atload'_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

zinit ice wait lucid blockf
zinit light zsh-users/zsh-completions

zinit ice wait lucid
zinit light zsh-users/zsh-syntax-highlighting

zinit cdreplay -q
autoload -Uz compinit
if [[ -n "$HOME/.zcompdump"(#qNmh-24) ]]; then
  compinit -C -d "$HOME/.zcompdump"
else
  compinit -d "$HOME/.zcompdump"
fi
compdef kubecolor=kubectl

autoload zmv
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^e' edit-command-line
bindkey ' ' magic-space

HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt sharehistory

typeset -U path
path+=("$HOME/.cargo/bin")
path+=("$HOME/.ghcup/bin")
path+=("$HOME/.go/bin")
path+=("$HOME/.jai/bin")
path+=("$HOME/.local/bin")

export PATH
export GOPATH="$HOME/.go"
export EDITOR=nvim
export SHELL=zsh

alias cat="bat"
alias cd="z"
alias convert="magick"
alias cp="cp -v"
alias downgrade="sudo downgrade"
alias hermes-tui="hermes --tui"
alias kubectl="kubecolor"
alias l="eza -lh"
alias la="eza -lah"
alias ldocker="lazydocker"
alias lgit="lazygit"
alias lgithub="gh-dash"
alias ljournal="lazyjournal"
alias ls="eza"
alias lt="eza -lah --tree"
alias mkdir="mkdir -pv"
alias mv="mv -v"
alias pacman="sudo pacman"
alias rm="trash -v"
alias sshnb="ssh luca@192.168.178.73"
alias sshpc="ssh luca@192.168.178.138"
alias toroff="sudo systemctl stop tor-router.service"
alias toron="sudo systemctl start tor-router.service"

fastfetch

eval "$(mise activate zsh)"
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
eval "$(zoxide init zsh)"
