set -g @wal_background "{background}"
set -g @wal_foreground "{foreground}"
set -g @wal_color1 "{color1}"
set -g @wal_color2 "{color2}"
set -g @wal_color4 "{color4}"

set -g popup-style "bg={background}"
set -g popup-border-style "fg={color1}"
set -g status-style "bg={background},fg={foreground}"
set -g pane-active-border-style "bg=default,fg={color4}"
set -g pane-border-style "fg={color1}"
set -g message-style "bg={background},fg={foreground}"
set -g mode-style "bg={color4},fg={background}"
