#!/usr/bin/env python3
"""Generate a Hermes skin from the wallpaper palette; --activate selects it."""

import os
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "lib"))

from palette import (  # noqa: E402
    TEXT_RATIO,
    contrast,
    dim_toward,
    hex_to_rgb,
    lift,
    mix,
    readable_on,
    rgb_to_hex,
    semantic,
    tone_map,
    vivify,
    wal_load,
    write_atomic,
)

WHITE = (1.0, 1.0, 1.0)

HERMES_HOME = os.environ.get("HERMES_HOME") or os.path.expanduser("~/.hermes")
SKIN_NAME = "wallust"
SKIN_DESCRIPTION = "Generated from the current wallpaper (wallust), do not hand-edit"
OUT = os.path.join(HERMES_HOME, "skins", SKIN_NAME + ".yaml")


def main():
    slot = wal_load("generate-hermes-skin")
    if slot is None:
        return 1

    bg = tone_map(slot("background", "#0b1019"))
    raw_fg = slot("foreground", "#c2c3c5")
    accent = vivify(slot("color4", "#B68B74"), 0.45, 0.55)
    alt = vivify(slot("color5", "#A76495"), 0.35, 0.55)
    cool = vivify(slot("color6", "#A76495"), 0.35, 0.55)

    status_bg = lift(bg, 0.045)
    menu_bg = lift(bg, 0.045)
    menu_current = lift(bg, 0.11)

    fg = readable_on(bg, raw_fg, 7.0)
    dim = dim_toward(fg, bg, 2.6)

    urgent = semantic("error", accent, bg)
    good = semantic("ok", accent, bg)
    warn = semantic("warn", accent, bg)

    diff_added_bg = mix(good, WHITE, 0.88)
    diff_removed_bg = mix(urgent, WHITE, 0.88)

    def on(surface, colour, ratio=TEXT_RATIO):
        return rgb_to_hex(readable_on(surface, colour, ratio), "#")

    def hx(c):
        return rgb_to_hex(c, "#")

    palette = {
        # no background key: tui would paint it opaque via osc 11
        "banner_border": on(bg, accent, 3.0),
        "banner_title": on(bg, accent, 4.5),
        "banner_accent": on(bg, accent, 4.5),
        "banner_dim": hx(dim),
        "banner_text": hx(fg),

        "ui_accent": on(bg, accent, 4.5),
        "ui_label": on(bg, alt, 4.5),
        "ui_ok": on(bg, good, 4.5),
        "ui_error": on(bg, urgent, 4.5),
        "ui_warn": on(bg, warn, 4.5),
        "ui_tool": on(bg, accent, 4.5),
        "ui_thinking": hx(dim),

        # word colours sit on the pale diff fill, not on bg
        "diff_added": hx(diff_added_bg),
        "diff_removed": hx(diff_removed_bg),
        "diff_added_word": on(diff_added_bg, good, 4.5),
        "diff_removed_word": on(diff_removed_bg, urgent, 4.5),

        "syntax_string": on(bg, good, 4.5),
        "syntax_number": on(bg, cool, 4.5),
        "syntax_keyword": on(bg, accent, 4.5),
        "syntax_comment": hx(dim),

        "prompt": hx(fg),
        "input_rule": on(bg, accent, 3.0),
        "response_border": on(bg, accent, 3.0),
        "session_label": on(bg, alt, 4.5),
        "session_border": hx(dim),

        "status_bar_bg": hx(status_bg),
        "status_bar_text": on(status_bg, raw_fg, 4.5),
        "status_bar_strong": on(status_bg, accent, 4.5),
        "status_bar_dim": on(status_bg, raw_fg, 2.4),
        "status_bar_good": on(status_bg, good, 4.5),
        "status_bar_warn": on(status_bg, warn, 4.5),
        "status_bar_bad": on(status_bg, warn, 4.5),
        "status_bar_critical": on(status_bg, urgent, 4.5),

        "voice_status_bg": hx(status_bg),
        "selection_bg": hx(menu_current),
        "completion_menu_bg": hx(menu_bg),
        "completion_menu_current_bg": hx(menu_current),
        "completion_menu_meta_bg": hx(menu_bg),
        "completion_menu_meta_current_bg": hx(menu_current),
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    lines = [
        "# generated by configs/base/wallust/scripts/generate-hermes-skin.py on every wallpaper switch, do not edit",
        "name: %s" % SKIN_NAME,
        'description: "%s"' % SKIN_DESCRIPTION,
        "colors:",
    ]
    lines += ['  %s: "%s"' % (key, value) for key, value in palette.items()]
    write_atomic(OUT, "\n".join(lines) + "\n")

    if "--report" in sys.argv:
        checks = [
            ("banner_text", "background"), ("ui_accent", "background"),
            ("ui_error", "background"), ("ui_ok", "background"),
            ("ui_warn", "background"), ("status_bar_text", "status_bar_bg"),
            ("status_bar_strong", "status_bar_bg"),
            ("status_bar_critical", "status_bar_bg"),
        ]
        for f, b in checks:
            back = palette.get(b, hx(bg))
            ratio = contrast(hex_to_rgb(palette[f]), hex_to_rgb(back))
            print("%-20s %s on %s  %.2f:1  %s"
                  % (f, palette[f], back, ratio,
                     "OK" if ratio >= TEXT_RATIO else "LOW"))

    print("wrote %s (%d colours)" % (OUT, len(palette)))

    if "--activate" in sys.argv:
        try:
            subprocess.run(["hermes", "skin", "use", SKIN_NAME],
                           check=False, timeout=60,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print("activated skin '%s'" % SKIN_NAME)
        except (OSError, subprocess.SubprocessError) as exc:
            print("could not activate: %s" % exc, file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
