#!/usr/bin/env bash
set -euo pipefail

COLORS_JSON="$HOME/.cache/wal/colors.json"
THEME="$HOME/.config/btop/themes/pywal.theme"

[[ -f "$COLORS_JSON" ]] || exit 0
command -v jq >/dev/null || exit 0

j() { jq -r "$1" "$COLORS_JSON"; }

bg=$(j '.special.background')
fg=$(j '.special.foreground')

c1=$(j '.colors.color1')
c2=$(j '.colors.color2')
c3=$(j '.colors.color3')
c4=$(j '.colors.color4')
c5=$(j '.colors.color5')
c6=$(j '.colors.color6')
c8=$(j '.colors.color8')

accent="$c4"

mkdir -p "$(dirname "$THEME")"

# ~/.config/btop is a repo symlink, so this also updates the committed seed
cat > "$THEME" <<EOF
# pywal theme for btop -- GENERATED by generate-btop-theme.sh, edits are overwritten on wallpaper switch.
theme[main_bg]="$bg"
theme[main_fg]="$fg"
theme[title]="$accent"
theme[hi_fg]="$accent"
theme[selected_bg]="$accent"
theme[selected_fg]="$bg"
theme[inactive_fg]="$c8"
theme[graph_text]="$fg"
theme[meter_bg]="$c8"
theme[proc_misc]="$c6"

# one palette hue per box, dim divider
theme[cpu_box]="$c4"
theme[mem_box]="$c6"
theme[net_box]="$c5"
theme[proc_box]="$c2"
theme[div_line]="$c8"

# temperature: green through amber to red
theme[temp_start]="$c2"
theme[temp_mid]="$c3"
theme[temp_end]="$c1"

# cpu load: blue through magenta to red
theme[cpu_start]="$c4"
theme[cpu_mid]="$c5"
theme[cpu_end]="$c1"

# memory: free green, used amber to red, available and cached cool hues
theme[free_start]="$c2"
theme[free_mid]="$c6"
theme[free_end]="$c4"
theme[used_start]="$c3"
theme[used_mid]="$c1"
theme[used_end]="$c1"
theme[available_start]="$c6"
theme[available_mid]="$c4"
theme[available_end]="$c5"
theme[cached_start]="$c5"
theme[cached_mid]="$c4"
theme[cached_end]="$c6"

# network: download cyan to blue, upload magenta to red
theme[download_start]="$c6"
theme[download_mid]="$c4"
theme[download_end]="$c5"
theme[upload_start]="$c5"
theme[upload_mid]="$c1"
theme[upload_end]="$c3"

# process list sweeps the accent hues
theme[process_start]="$c4"
theme[process_mid]="$c6"
theme[process_end]="$c2"
EOF
