#:schema https://yazi-rs.github.io/schemas/yazi.json

# image preview unset so yazi auto-detects the protocol

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_dir_first = true
sort_sensitive = false
sort_reverse   = false
linemode       = "size"
show_hidden    = false
show_symlink   = true
scrolloff      = 5

[preview]
wrap          = "no"
image_delay   = 20
image_quality = 90
