[preferred]
default=hyprland;kde
org.freedesktop.impl.portal.Secret=gnome-keyring
org.freedesktop.impl.portal.Notification=plasmanotify
# kde/gtk screencast backends show nothing here
org.freedesktop.impl.portal.ScreenCast=hyprland
org.freedesktop.impl.portal.ScreenShot=hyprland
