#!/usr/bin/env bash

set_wallpaper() {
    local file="$1"

    # Background.qml refreshes on startup or over IPC only — it does not watch
    # the symlink — so the shell has to be told, not just pointed at the file.
    ln -sf "$file" "$HOME/.cache/wal/wallpaper" 2>/dev/null
    echo "$file" > "$HOME/.cache/wal/wallpaper_path" 2>/dev/null

    # A dead shell just reads the symlink on its next start, so failure here is
    # not worth reporting.
    timeout 3 quickshell ipc -p "$HOME/.config/quickshell" \
        call background set "$file" >/dev/null 2>&1 || true

    # A theme wallpaper is a handwritten theme's own background: selecting one
    # must apply that theme's hand-authored palette rather than re-derive a
    # palette from the image. Matched on each theme JSON's own "wallpaper"
    # field, so a theme and its wallpaper need no matching basenames.
    THEME_DIR="$HOME/projects/arch-dotfiles/themes"
    FILE_REAL=$(readlink -f "$file" 2>/dev/null || echo "$file")
    THEME_JSON=""
    THEME_NAME=""
    for jf in "$THEME_DIR"/*.json; do
        [[ -e "$jf" ]] || continue
        wp=$(jq -r '.wallpaper // empty' "$jf" 2>/dev/null)
        [[ -n "$wp" ]] || continue
        wp_real=$(readlink -f "$wp" 2>/dev/null || echo "$wp")
        if [[ "$wp_real" == "$FILE_REAL" ]]; then
            THEME_JSON="$jf"
            THEME_NAME=$(basename "${jf%.json}")
            break
        fi
    done
    if [[ -n "$THEME_JSON" ]]; then
        # `wallust cs` regenerates every downstream template (ghostty, kitty,
        # tmux, hyprlock's colors-rgb, …) from the theme's palette; copying
        # colors.json alone would leave all of them stale. The theme is
        # registered in wallust's colorschemes dir by configs/wallust/link.sh.
        # `-s` skips terminal escape sequences.
        wallust cs -s "$THEME_NAME"

        # Optional per-theme "font" field, applied through toggle-font.sh's own
        # `set` — the single place every font change in this repo goes through.
        THEME_FONT=$(jq -r '.font // empty' "$THEME_JSON" 2>/dev/null)
        if [[ -n "$THEME_FONT" ]]; then
            ~/projects/arch-dotfiles/toggles/toggle-font.sh set "$THEME_FONT" || true
        fi

        # nvim's theme dispatch keys off the theme's own name (lua/themes/
        # <name>.lua), falling back to pywal inside lua/theme.lua when there is
        # no matching file.
        NVIM_THEME="$THEME_NAME"
    else
        # -s skips terminal escape sequences, which wallust would otherwise
        # write to every open TTY.
        wallust run -s "$file"
        NVIM_THEME="pywal"
    fi
    # Read by lua/theme.lua at startup, and by the live nvim nudge below.
    printf '%s\n' "$NVIM_THEME" > "$HOME/.cache/wal/nvim_theme"

    # GTK/Qt themes. colors-oomox is generated by a script rather than a
    # wallust template because mapping GTK roles onto fixed palette slots needs
    # contrast maths, and pywal-syntax templates have none. Synchronous and
    # first: both exporters below read the file it writes.
    #
    # The exporters themselves are backgrounded — ~1.5s each, and nothing
    # downstream needs them finished, so GTK apps simply pick up the new colors
    # a moment after terminal apps do.
    ~/projects/arch-dotfiles/configs/wallust/scripts/generate-oomox-colors.py || true

    themix-multi-export ~/.config/oomox/export_config/multi_export_oomox_classic.json ~/.cache/wal/colors-oomox &
    themix-multi-export ~/.config/oomox/export_config/multi_export_oodwaita.json ~/.cache/wal/colors-oomox &

    # apply the new colors to other programs
    pywalfox update &
    pywal-spicetify wal &

    # The lua config reads ~/.cache/wal/colors itself, and hyprland does not
    # watch that file. config-only skips the monitor reload, which flickers the
    # outputs.
    hyprctl reload config-only &

    # update hyprlock config. $BACKGROUND_GLASS at the end of the chain takes
    # the same RGB as $BACKGROUND; its 0.55 alpha is a fixed design choice for
    # the input field's frosted-glass look and must not track the wallpaper.
    sed -i "s|\$BACKGROUND = rgb([^)]*)|\$BACKGROUND = rgb($(sed -n '1p' ~/.cache/wal/colors-rgb))|" ~/.config/hypr/hyprlock.conf && \
    sed -i "s|\$FOREGROUND = rgb([^)]*)|\$FOREGROUND = rgb($(sed -n '2p' ~/.cache/wal/colors-rgb))|" ~/.config/hypr/hyprlock.conf && \
    sed -i "s|\$COLOR1 = rgb([^)]*)|\$COLOR1 = rgb($(sed -n '3p' ~/.cache/wal/colors-rgb))|" ~/.config/hypr/hyprlock.conf && \
    sed -i "s|\$COLOR2 = rgb([^)]*)|\$COLOR2 = rgb($(sed -n '4p' ~/.cache/wal/colors-rgb))|" ~/.config/hypr/hyprlock.conf && \
    sed -i "s|\$COLOR3 = rgb([^)]*)|\$COLOR3 = rgb($(sed -n '5p' ~/.cache/wal/colors-rgb))|" ~/.config/hypr/hyprlock.conf && \
    sed -i "s|\$BACKGROUND_GLASS = rgba([^)]*)|\$BACKGROUND_GLASS = rgba($(sed -n '1p' ~/.cache/wal/colors-rgb),0.55)|" ~/.config/hypr/hyprlock.conf &

    # update zed and vscodium themes
    ~/projects/arch-dotfiles/configs/wallust/scripts/generate-editor-themes.sh &

    # No chat-client theming: Telegram needs a manual GUI confirmation for a
    # palette file (tdesktop#31183), ZapZap hardcodes its palette, and Signal
    # exposes no theming hook at all.

    # Hermes agent: one YAML skin themes its CLI, TUI and desktop app at once,
    # so this rewrites a single file rather than driving three integrations.
    ~/projects/arch-dotfiles/configs/wallust/scripts/generate-hermes-skin.py >/dev/null 2>&1 &

    # KDE/Qt colours + Plasma's wallpaper. Qt apps reach this through
    # QT_QPA_PLATFORMTHEME=kde -> plasma-integration -> ~/.config/kdeglobals.
    ~/projects/arch-dotfiles/configs/wallust/scripts/generate-kde-theme.sh "$file" &

    # update discord theme
    sed -i "s|\--accentcolor: .*$|\--accentcolor: $(sed -n '2p' ~/.cache/wal/colors-rgb);|" ~/.config/BetterDiscord/themes/wal.theme.css && \
    sed -i "s|\--accentcolor2: .*$|\--accentcolor2: $(sed -n '2p' ~/.cache/wal/colors-rgb);|" ~/.config/BetterDiscord/themes/wal.theme.css && \
    sed -i "s|\--backgroundprimary: .*$|\--backgroundprimary: $(sed -n '1p' ~/.cache/wal/colors-rgb);|" ~/.config/BetterDiscord/themes/wal.theme.css && \
    sed -i "s|\--backgroundsecondary: .*$|\--backgroundsecondary: $(sed -n '1p' ~/.cache/wal/colors-rgb);|" ~/.config/BetterDiscord/themes/wal.theme.css && \
    sed -i "s|\--backgroundsecondaryalt: .*$|\--backgroundsecondaryalt: $(sed -n '1p' ~/.cache/wal/colors-rgb);|" ~/.config/BetterDiscord/themes/wal.theme.css && \
    sed -i "s|\--backgroundtertiary: .*$|\--backgroundtertiary: $(sed -n '1p' ~/.cache/wal/colors-rgb);|" ~/.config/BetterDiscord/themes/wal.theme.css &

    # The font is read from toggle-font.sh, never hardcoded: this script owns
    # colours and must not reset the desktop font behind a wallpaper switch.
    # A failed or empty read means "leave the font alone" rather than writing a
    # half-formed "<family> " or " 10" into gsettings and both settings.ini.
    ui_family=$(~/projects/arch-dotfiles/toggles/toggle-font.sh get 2>/dev/null || true)
    ui_size=$(~/projects/arch-dotfiles/toggles/toggle-font.sh ui-size 2>/dev/null || true)
    if [[ -n "$ui_family" && "$ui_size" =~ ^[0-9]+$ ]]; then
        ui_font="$ui_family $ui_size"
    else
        ui_font=""
    fi

    gsettings set org.gnome.desktop.interface gtk-theme 'oomox-colors-oomox'
    [[ -n "$ui_font" ]] && gsettings set org.gnome.desktop.interface font-name "$ui_font"
    theme=$(gsettings get org.gnome.desktop.interface gtk-theme)
    gsettings set org.gnome.desktop.interface gtk-theme '' && gsettings set org.gnome.desktop.interface gtk-theme "$theme" &

    # apps that read gtk-3.0/gtk-4.0 settings.ini directly instead of
    # gsettings (nwg-look used to be a manual step for exactly this)
    for gtkdir in "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"; do
        mkdir -p "$gtkdir"
        ini="$gtkdir/settings.ini"
        touch "$ini"
        grep -q "^\[Settings\]" "$ini" || printf '[Settings]\n' >> "$ini"
        if grep -q "^gtk-theme-name=" "$ini"; then
            sed -i "s|^gtk-theme-name=.*|gtk-theme-name=oomox-colors-oomox|" "$ini"
        else
            sed -i "/^\[Settings\]/a gtk-theme-name=oomox-colors-oomox" "$ini"
        fi
        # Skipped when the font read failed — see the guard above.
        if [[ -n "$ui_font" ]]; then
            if grep -q "^gtk-font-name=" "$ini"; then
                sed -i "s|^gtk-font-name=.*|gtk-font-name=$ui_font|" "$ini"
            else
                sed -i "/^\[Settings\]/a gtk-font-name=$ui_font" "$ini"
            fi
        fi
    done &

    # Push the active theme to every running nvim through the same
    # lua/theme.lua entry point startup uses, so open buffers recolour exactly
    # as a fresh launch would. NVIM_THEME is built above from a theme basename
    # or the literal "pywal", never untrusted input, so interpolating it into
    # the Lua string literal is safe.
    for addr in $XDG_RUNTIME_DIR/nvim.*; do
        nvim --server "$addr" --remote-send \
            "<Esc>:lua require('theme').apply('${NVIM_THEME}')<CR>" &
    done

    # Re-source the generated tmux colours on every running server, so open
    # sessions recolour without a restart. `-q` and `|| true`: there is
    # usually no tmux server at all.
    if command -v tmux >/dev/null 2>&1 && tmux list-sessions >/dev/null 2>&1; then
        tmux source-file ~/.cache/wal/colors-tmux.conf >/dev/null 2>&1 || true
    fi

    # kitty reloads its config on SIGUSR1; without this an open kitty keeps
    # the old palette even though colors-kitty.conf was regenerated.
    pkill -USR1 -x kitty >/dev/null 2>&1 || true

    # Ghostty has no config-file watcher, so touching its config does nothing;
    # its reload_config action is only reachable over D-Bus. Best-effort:
    # harmless if ghostty isn't running or D-Bus is unavailable.
    gdbus call --session --dest com.mitchellh.ghostty \
        --object-path /com/mitchellh/ghostty \
        --method org.gtk.Actions.Activate reload-config '[]' '{}' \
        >/dev/null 2>&1 || true

    # No notification-daemon restart: quickshell's notifications plugin
    # recolours live from Commons/Color.qml, which watches colors.json itself.
}

# A dmenu-style picker is plain text only, so the interactive picker below uses
# fzf's preview pane with chafa over a cached vipsthumbnail JPEG instead.
wallpaper_thumb() {
    local file="$1" thumb_dir="$HOME/.cache/wal/wallpaper-thumbs"
    mkdir -p "$thumb_dir"
    local key thumb
    key=$(stat -c '%Y-%s' "$file" 2>/dev/null)
    thumb="$thumb_dir/$(basename "$file").$key.jpg"
    if [[ ! -f "$thumb" ]]; then
        find "$thumb_dir" -name "$(basename "$file").*.jpg" -delete 2>/dev/null
        vipsthumbnail "$file" -s 480 -o "${thumb%.jpg}.jpg[Q=80]" 2>/dev/null
    fi
    [[ -f "$thumb" ]] && echo "$thumb" || echo "$file"
}
export -f wallpaper_thumb

main() {
    WALLPAPER_DIR="$HOME/projects/arch-dotfiles/wallpapers"
    export WALLPAPER_DIR

    # Non-interactive surface for the native picker (quickshell's
    # image-picker plugin), ahead of the fzf path so the panel never has to
    # know about fzf.
    case "${1:-}" in
    get)
        readlink -f "$HOME/.cache/wal/wallpaper" 2>/dev/null || true
        exit 0
        ;;
    list)
        find "$WALLPAPER_DIR" -type f \
            \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.gif" \) \
            | sort
        exit 0
        ;;
    set)
        [[ -n "${2:-}" && -f "$2" ]] || { echo "usage: $(basename "$0") set <file>" >&2; exit 1; }
        set_wallpaper "$2"
        exit 0
        ;;
    esac

    WALLPAPERS="$(find "$WALLPAPER_DIR" \
        -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.gif" \) \
        -exec basename {} \; \
        | sort)\
    "

    # use cli provided wallpaper filepath
    if [[ -n "$1" ]]; then
        if [[ ! -f "$1" && "$1" != "random" ]]; then
            echo "File does not exist: $1"
            exit 1
        fi

        if [[ "$1" == "random" ]]; then
            set_wallpaper "$WALLPAPER_DIR/$(shuf -n 1 <<< "$WALLPAPERS")"
            exit 0
        fi

        set_wallpaper "$1"
        exit 0
    fi

    # Interactive selection: the fzf preview pane renders a real thumbnail.
    SELECTED=$(printf "%s\nrandom\n" "$WALLPAPERS" | fzf \
        --prompt="wallpaper> " \
        --preview-window="right:60%" \
        --preview '
            if [[ "{}" == "random" ]]; then
                echo "(random)"
            else
                chafa --size="${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}" \
                    "$(wallpaper_thumb "$WALLPAPER_DIR/{}")" 2>/dev/null
            fi
        ')

    if [[ "$SELECTED" == "CNCLD" || -z "$SELECTED" ]]; then
        echo "No wallpaper selected."
        exit 0
    fi

    if [[ "$SELECTED" == "random" ]]; then
        SELECTED_FILE="$WALLPAPER_DIR/$(shuf -n 1 <<< "$WALLPAPERS")"
    else
        SELECTED_FILE="$WALLPAPER_DIR/$SELECTED"
    fi

    set_wallpaper "$SELECTED_FILE"
    exit 0
}

main "$@"
