# nmap needs -sT, no raw syn/udp through proxychains
strict_chain

# no direct dns leak
proxy_dns

tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
# must match ANONYMOUS_SOCKS_PORT
socks5 127.0.0.1 9061
