plugin {
    dynamic-cursors {
        enabled = true
        mode    = none

        shake {
            effects   = true
            threshold = 4
            timeout   = 500
        }

        hyprcursor {
            enabled    = true
            nearest    = true
            resolution = -1
            fallback   = clientside
        }
    }

    overview {
        showEmptyWorkspace = 0
        showNewWorkspace   = 0
        centerAligned      = 1
        exitOnClick        = 1
        exitOnSwitch       = 1
        panelHeight        = 250
        affectStrut        = 0
        panelColor                  = rgba(00000066)
        workspaceActiveBackground   = rgba(00000066)
        workspaceInactiveBackground = rgba(00000099)
    }

    hyprscrolling {
        column_width = 0.8
        fullscreen_on_one_column = true
    }
}
