exec-once = uwsm finalize

# long-running apps -> scoped systemd units
exec-once = uwsm app -- awww-daemon
exec-once = uwsm app -- copyq --start-server
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- mako
exec-once = uwsm app -- waybar

# oneshots, leave bare
exec-once = hyprpm reload
exec-once = xhost + local:
exec-once = xhost +SI:localuser:root

# has to be in that order
exec-once = uwsm app -- elephant
exec-once = uwsm app -- walker --gapplication-service
